### ISSUE TITLE
Peer to Peer code review wk.7

### ISSUE THREAD

**Issue by Bavon101** [jssol/todo-list#4]
@jssol Your project really looks amazing and unique, there is just some minor bug I spotted.

- [x] Your input field allows users to enter and add empty spaces as a task, I think removing white spaces from the input value by calling the `trim` method and checking on the value `length` will solve this.

Cheers and happy coding 🐱‍💻🐱‍🏍.

**Comment by jssol** [comment]
@Bavon101

Thanks a lot for the feedback.
I have successfully implemented the suggested change :+1: :tada:
